#!/usr/bin/env bash
# check-installed-skill-drift.sh — detect BIDIRECTIONAL drift between the repo
# skill tree (skills/) and the globally installed skill tree
# (~/.claude/skills/ by default).
#
# Lattice dogfoods itself through the installed tree. Silent staleness — an
# installed ensure-lattice.sh that exits 2 silently while the repo ships a
# 296-line version, or an install that is a mix of older and newer-than-repo
# content — undermines every skill-level guarantee. This script FAILS LOUD:
# exit 1 with an actionable inventory on any mismatch, never a silent exit 2.
#
# The check is bidirectional and NEVER auto-clobbers. It reports three
# categories so the operator decides the refresh action (the install may hold
# local/newer content a blind overwrite would destroy — see docs/getting-started.md
# (monorepo, when present) § Refresh install.
# § Refresh install):
#   - repo-only      file present in repo, absent from install  (install is stale)
#   - install-only   file present in install, absent from repo  (local edit OR
#                    stale generated artifact, e.g. __pycache__)
#   - differs        content mismatch                           (review the diff;
#                    either side may be newer — do not assume)
#
# A skill dir present in the repo but missing entirely from the install is
# reported as `skill-absent-install` (the whole skill is stale/missing).
#
# Non-Lattice skills that happen to live in the install dir (e.g. bailian-cli,
# ego-browser) are OUT OF SCOPE: the repo skills/ dir is the source of truth
# for which skills are "Lattice skills", and only those are compared.
#
# Generated bytecode (__pycache__/**, *.pyc) is ignored to keep the signal
# clean — it is not source and is recreated on run.
#
# Env:
#   LATTICE_SKILL_ROOT            repo skills/ dir
#                                 (default: resolved from this script's location)
#   LATTICE_INSTALLED_SKILL_HOME  installed skills dir
#                                 (default: $HOME/.claude/skills)
# Flags:
#   --skill-root DIR      override repo skills/ dir
#   --installed-dir DIR   override installed skills dir
#   --json                machine-readable single-object output
#   --check-only          no-op alias (the script never writes); for ergonomics
#   -h, --help            print this header
#
# Exit codes:
#   0  in sync (no drift)
#   1  drift detected (loud, actionable) — NEVER use 2 for drift
#   2  misuse (bad arguments / missing dirs)
#
# See: tkt-196, docs/getting-started.md (monorepo, when present) § Refresh install.

set -euo pipefail

SCRIPT_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Repo skills/ dir = two levels up from scripts/ (_lattice-lib -> skills).
# spc-254 A9: the default must resolve to skills/, not the repo root — an extra
# `..` made the dev-mode drift check compare top-level dirs (.github, docs, …)
# against the install and report them as skill-absent. cd -P follows symlinks,
# so the installed copy (a symlinked _lattice-lib) also resolves correctly.
DEFAULT_SKILL_ROOT="$(cd -P "$SCRIPT_DIR/../.." && pwd)"

SKILL_ROOT="${LATTICE_SKILL_ROOT:-$DEFAULT_SKILL_ROOT}"
INSTALLED_HOME="${LATTICE_INSTALLED_SKILL_HOME:-$HOME/.claude/skills}"
JSON=0
CHECK_ONLY=0

print_help() {
  sed -n '2,/^set -euo pipefail$/p' "$0" | sed 's/^# \?//' | sed '/^set -euo pipefail$/d'
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --skill-root)     SKILL_ROOT="${2:?--skill-root requires a dir}"; shift 2 ;;
    --installed-dir)  INSTALLED_HOME="${2:?--installed-dir requires a dir}"; shift 2 ;;
    --json)           JSON=1; shift ;;
    --check-only)     CHECK_ONLY=1; shift ;;
    -h|--help)        print_help; exit 0 ;;
    *) echo "Error: unknown argument: $1 (try --help)" >&2; exit 2 ;;
  esac
done
# --check-only is a no-op: this script never writes. Kept so callers/operators
# can express intent compatibly with ensure-lattice.sh --check-only.
: "$CHECK_ONLY"

if [[ ! -d "$SKILL_ROOT" ]]; then
  echo "Error: repo skill root not found: $SKILL_ROOT (set LATTICE_SKILL_ROOT or --skill-root)" >&2
  exit 2
fi
if [[ ! -d "$INSTALLED_HOME" ]]; then
  echo "Error: installed skill home not found: $INSTALLED_HOME (set LATTICE_INSTALLED_SKILL_HOME or --installed-dir)" >&2
  exit 2
fi

SKILL_ROOT="$(cd -P "$SKILL_ROOT" && pwd)"
INSTALLED_HOME="$(cd -P "$INSTALLED_HOME" && pwd)"

# The set of Lattice skills = the subdirs shipped in the repo skills/ dir.
# This is the source of truth; non-Lattice skills in the install are skipped.
# (no mapfile/readarray: macOS system bash is 3.2 — see ratify.sh)
SKILLS=()
while IFS= read -r d; do
  [[ -z "$d" ]] && continue
  SKILLS+=("$d")
done < <(find "$SKILL_ROOT" -mindepth 1 -maxdepth 1 -type d | sort)
if [[ ${#SKILLS[@]} -eq 0 ]]; then
  echo "Error: no skill dirs under $SKILL_ROOT" >&2
  exit 2
fi

# $1 = skill root, $2 = skill name -> sorted relative file list, excluding
# generated bytecode. Uses -L because installed skill dirs are typically
# symlinks (e.g. ~/.claude/skills/_lattice-lib -> ../../.agents/skills/...);
# BSD/macOS find does not follow a symlinked start point without -L.
rel_files() {
  local root="$1" skill="$2"
  # `|| true` swallows a nonzero find exit (an unreadable subdir makes find
  # exit nonzero even with stderr suppressed); under pipefail+set -e that
  # nonzero would abort the pipeline and leak the caller's mktemp (tkt-242 L3).
  # find still emits every readable file before exiting, so the output stays
  # complete — only the spurious failure is suppressed.
  find -L "$root/$skill" \( -path '*/__pycache__/*' -o -name '*.pyc' \) -prune \
    -o -type f -print 2>/dev/null \
    | sed "s|^$root/$skill/||" | LC_ALL=C sort || true
}

repo_only=()
install_only=()
differs=()
skill_absent=()
total_drift=0

for s_full in "${SKILLS[@]}"; do
  s="$(basename "$s_full")"
  if [[ ! -d "$INSTALLED_HOME/$s" ]]; then
    skill_absent+=("$s")
    total_drift=$((total_drift + 1))
    continue
  fi
  repo_set=$(mktemp); inst_set=$(mktemp)
  # Defensive cleanup: even with the rel_files `|| true` fix, ensure these
  # mktemp files are removed if any command below aborts under set -e (a
  # future cause would otherwise leak both temp files across long runs).
  # The variables hold the current iteration's paths at EXIT; on normal
  # completion they were already rm'd, so the trap no-ops. tkt-242 L3.
  trap 'rm -f "$repo_set" "$inst_set"' EXIT
  rel_files "$SKILL_ROOT" "$s" >"$repo_set"
  rel_files "$INSTALLED_HOME" "$s" >"$inst_set"

  while IFS= read -r f; do
    [[ -z "$f" ]] && continue
    repo_only+=("$s/$f"); total_drift=$((total_drift + 1))
  done < <(comm -23 "$repo_set" "$inst_set")

  while IFS= read -r f; do
    [[ -z "$f" ]] && continue
    install_only+=("$s/$f"); total_drift=$((total_drift + 1))
  done < <(comm -13 "$repo_set" "$inst_set")

  while IFS= read -r f; do
    [[ -z "$f" ]] && continue
    if ! cmp -s "$SKILL_ROOT/$s/$f" "$INSTALLED_HOME/$s/$f" 2>/dev/null; then
      differs+=("$s/$f"); total_drift=$((total_drift + 1))
    fi
  done < <(comm -12 "$repo_set" "$inst_set")

  rm -f "$repo_set" "$inst_set"
done

# json-encode a bash array of strings
arr_json() {
  printf '['
  local i=0
  for f in "$@"; do
    [[ $i -gt 0 ]] && printf ','
    local escaped="${f//\\/\\\\}"
    printf '"%s"' "${escaped//\"/\\\"}"
    i=$((i + 1))
  done
  printf ']'
}

if [[ $JSON -eq 1 ]]; then
  drift_flag="false"; [[ $total_drift -gt 0 ]] && drift_flag="true"
  # bash 3.2 + set -u errors on expanding an empty array ("${a[@]}"); guard.
  sa_json="[]"; ro_json="[]"; io_json="[]"; di_json="[]"
  [[ ${#skill_absent[@]} -gt 0 ]] && sa_json=$(arr_json "${skill_absent[@]}")
  [[ ${#repo_only[@]}    -gt 0 ]] && ro_json=$(arr_json "${repo_only[@]}")
  [[ ${#install_only[@]} -gt 0 ]] && io_json=$(arr_json "${install_only[@]}")
  [[ ${#differs[@]}      -gt 0 ]] && di_json=$(arr_json "${differs[@]}")
  printf '{"skill_root":"%s","installed_home":"%s","skills_compared":%d,"drift":%s,"skill_absent_install":%s,"repo_only":%s,"install_only":%s,"differs":%s}\n' \
    "$SKILL_ROOT" "$INSTALLED_HOME" "${#SKILLS[@]}" "$drift_flag" \
    "$sa_json" "$ro_json" "$io_json" "$di_json"
else
  echo "Lattice installed-skill drift check"
  echo "  repo skill root : $SKILL_ROOT"
  echo "  installed home  : $INSTALLED_HOME"
  echo "  skills compared  : ${#SKILLS[@]}"
  echo
  if [[ $total_drift -eq 0 ]]; then
    echo "STATUS: in sync — no drift detected."
  else
    echo "STATUS: DRIFT DETECTED — $total_drift mismatch(es). Do NOT blindly overwrite the install;"
    echo "        some install-only or differing files may be newer local edits. Review, then refresh."
    echo
    if [[ ${#skill_absent[@]} -gt 0 ]]; then
      echo "## skill-absent-install (whole skill missing from install — stalest case):"
      for f in "${skill_absent[@]}"; do printf '  - %s\n' "$f"; done
      echo
    fi
    if [[ ${#repo_only[@]} -gt 0 ]]; then
      echo "## repo-only (in repo, ABSENT from install — install is stale; refresh pulls these in):"
      for f in "${repo_only[@]}"; do printf '  - %s\n' "$f"; done
      echo
    fi
    if [[ ${#install_only[@]} -gt 0 ]]; then
      echo "## install-only (in install, ABSENT from repo — local edit OR stale artifact; do not clobber blindly):"
      for f in "${install_only[@]}"; do printf '  - %s\n' "$f"; done
      echo
    fi
    if [[ ${#differs[@]} -gt 0 ]]; then
      echo "## differs (content mismatch — review the diff; either side may be newer):"
      for f in "${differs[@]}"; do printf '  - %s\n' "$f"; done
      echo
    fi
    echo "Refresh: see docs/getting-started.md (monorepo, when present) § Refresh install."
    echo "  full pack : npx skills add percena/lattice -a claude-code -a codex -g -y"
    echo "  local tip : npx skills add /path/to/lattice --skill _lattice-lib --skill start-work \\"
    echo "              --skill create-spec --skill create-review --skill create-tickets \\"
    echo "              --skill create-pr --skill finish-work -a claude-code -a codex -g -y"
    echo "  Claude    : claude plugin marketplace remove percena 2>/dev/null || true; reinstall lattice@percena"
  fi
fi

if [[ $total_drift -gt 0 ]]; then
  exit 1
fi
exit 0
