#!/usr/bin/env bash
# Detect uncommitted Lattice residue on the MAIN checkout (team base tree).
#
# Typical pollution: binder + lineage written on base before ensure-workspace,
# left behind while work continues in a sibling worktree — then blocks pull.
#
# Usage:
#   check-base-residue.sh [--main-root <path>] [--json] [--strict]
#
# Exit: 0 if clean (or non-strict with residue); 1 if --strict and residue found; 2 usage
set -euo pipefail

MAIN_ROOT=""
AS_JSON=false
STRICT=false

usage() {
  cat >&2 <<'EOF'
Usage: check-base-residue.sh [--main-root <path>] [--json] [--strict]
EOF
  exit 2
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --main-root) MAIN_ROOT="${2:-}"; shift 2 ;;
    --json) AS_JSON=true; shift ;;
    --strict) STRICT=true; shift ;;
    -h|--help) usage ;;
    *) echo "Unknown: $1" >&2; usage ;;
  esac
done

# --json renders via python3: preflight before doing any work so the check
# cannot run to completion and then die 127 mid-emission (style matches
# ensure-workspace.sh preflight).
if $AS_JSON && ! command -v python3 >/dev/null 2>&1; then
  echo "Error: python3 is required by check-base-residue.sh --json" >&2
  exit 2
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
if [[ -f "$SCRIPT_DIR/_lattice-home.sh" ]]; then
  source "$SCRIPT_DIR/_lattice-home.sh"
fi

if [[ -z "$MAIN_ROOT" ]]; then
  if type lattice_main_root >/dev/null 2>&1; then
    MAIN_ROOT=$(lattice_main_root 2>/dev/null || true)
  fi
fi
if [[ -z "$MAIN_ROOT" ]]; then
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    MAIN_ROOT=$(git rev-parse --show-toplevel)
  else
    echo "Error: cannot resolve main root" >&2
    exit 2
  fi
fi
MAIN_ROOT=$(cd "$MAIN_ROOT" && pwd)

LATTICE="$MAIN_ROOT/.lattice"
ITEMS=()

if git -C "$MAIN_ROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  # Tracked + untracked under .lattice
  if [[ -d "$LATTICE" ]]; then
    while IFS= read -r line; do
      [[ -n "$line" ]] && ITEMS+=("$line")
    done < <(git -C "$MAIN_ROOT" status --porcelain -- .lattice 2>/dev/null || true)
  fi

  # Lattice-related non-.lattice paths that still block pull.
  # .gitignore: dirty when it already carries Lattice rules/marker (ensure-lattice / init).
  GI="$MAIN_ROOT/.gitignore"
  if [[ -f "$GI" ]] && git -C "$MAIN_ROOT" status --porcelain -- .gitignore 2>/dev/null | grep -q .; then
    if grep -qE 'Lattice \(generated by lattice-init|\.lattice/lineage/by-id/|\.lattice/\.ids/' "$GI" 2>/dev/null; then
      while IFS= read -r line; do
        [[ -n "$line" ]] && ITEMS+=("$line")
      done < <(git -C "$MAIN_ROOT" status --porcelain -- .gitignore 2>/dev/null || true)
    fi
  fi
fi

# Summarize
COUNT=${#ITEMS[@]}
HAS_RESIDUE=false
[[ $COUNT -gt 0 ]] && HAS_RESIDUE=true

# Branch on main checkout (informational)
MAIN_BRANCH=$(git -C "$MAIN_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")

if $AS_JSON; then
  python3 - "$MAIN_ROOT" "$HAS_RESIDUE" "$MAIN_BRANCH" "${ITEMS[@]+"${ITEMS[@]}"}" <<'PY'
import json, sys
main, has, branch = sys.argv[1], sys.argv[2] == "true", sys.argv[3]
items = sys.argv[4:]
print(json.dumps({
  "ok": not has,
  "has_residue": has,
  "main_root": main,
  "main_branch": branch or None,
  "count": len(items),
  "items": items,
  "hint": None if not has else (
    "MAIN checkout has uncommitted Lattice-related changes (.lattice and/or Lattice .gitignore). "
    "If you already ship from a worktree, discard or commit residue on base only after intentional base bookkeeping; "
    "do not leave pre-worktree binder/lineage/gitignore dirt that blocks git pull."
  ),
}, indent=2))
PY
else
  if $HAS_RESIDUE; then
    echo "check-base-residue: FOUND residue on MAIN checkout" >&2
    echo "  main:   $MAIN_ROOT" >&2
    echo "  branch: ${MAIN_BRANCH:-?}" >&2
    echo "  count:  $COUNT" >&2
    for it in "${ITEMS[@]}"; do
      echo "  - $it" >&2
    done
    echo "  hint: discard accidental pre-worktree L0 dirt, or commit intentional finish-work bookkeeping" >&2
  else
    echo "check-base-residue: clean"
    echo "  main: $MAIN_ROOT"
  fi
fi

if $STRICT && $HAS_RESIDUE; then
  exit 1
fi
exit 0
