#!/usr/bin/env bats
# bats tests for ensure-lattice.sh

setup_file() {
  REPO_ROOT="$(cd "$(dirname "$BATS_TEST_FILENAME")/../../../.." && pwd)"
  export ENSURE="$REPO_ROOT/skills/_lattice-lib/scripts/ensure-lattice.sh"
}

setup() {
  TEST_DIR="$(mktemp -d "${TMPDIR:-/tmp}/ensure-lattice.XXXXXX")"
  export TEST_DIR
  mkdir -p "$TEST_DIR/repo"
}

teardown() {
  rm -rf "$TEST_DIR"
}

@test "initializes missing skeleton + config" {
  run bash "$ENSURE" --root "$TEST_DIR/repo" --json
  [ "$status" -eq 0 ]
  [[ -f "$TEST_DIR/repo/.lattice/config.yaml" ]]
  [[ -d "$TEST_DIR/repo/.lattice/specs" ]]
  [[ "$output" == *'"action": "initialized"'* ]] || [[ "$output" == *'"action":"initialized"'* ]]
  [[ "$output" == *'"ready": true'* ]] || [[ "$output" == *'"ready":true'* ]]
  grep -q 'profile: strict' "$TEST_DIR/repo/.lattice/config.yaml"
}

@test "second run reports ready and keeps profile" {
  bash "$ENSURE" --root "$TEST_DIR/repo" --profile light >/dev/null
  grep -q 'profile: light' "$TEST_DIR/repo/.lattice/config.yaml"
  run bash "$ENSURE" --root "$TEST_DIR/repo" --profile strict --json
  [ "$status" -eq 0 ]
  [[ "$output" == *'"action": "ready"'* ]] || [[ "$output" == *'"action":"ready"'* ]]
  grep -q 'profile: light' "$TEST_DIR/repo/.lattice/config.yaml"
}

@test "check-only fails before init and passes after" {
  run bash "$ENSURE" --root "$TEST_DIR/repo" --check-only
  [ "$status" -eq 1 ]
  bash "$ENSURE" --root "$TEST_DIR/repo" >/dev/null
  run bash "$ENSURE" --root "$TEST_DIR/repo" --check-only --json
  [ "$status" -eq 0 ]
  [[ "$output" == *'"ready": true'* ]] || [[ "$output" == *'"ready":true'* ]]
}

@test "default write-gitignore appends once" {
  : >"$TEST_DIR/repo/.gitignore"
  bash "$ENSURE" --root "$TEST_DIR/repo" >/dev/null
  grep -q 'Lattice (generated by lattice-init' "$TEST_DIR/repo/.gitignore"
  lines1=$(wc -l <"$TEST_DIR/repo/.gitignore")
  bash "$ENSURE" --root "$TEST_DIR/repo" >/dev/null
  lines2=$(wc -l <"$TEST_DIR/repo/.gitignore")
  [ "$lines1" -eq "$lines2" ]
}

@test "default initialization propagates the gitignore symlink refusal" {
  mkdir -p "$TEST_DIR/victim"
  printf 'keep-me\n' >"$TEST_DIR/victim/config.txt"
  ln -s ../victim/config.txt "$TEST_DIR/repo/.gitignore"

  run bash "$ENSURE" --root "$TEST_DIR/repo" --json

  [ "$status" -eq 1 ]
  [[ "$output" == *"refusing symlinked managed path"* ]]
  [[ "$output" == *"Lattice ensure failed"* ]]
  [ "$(cat "$TEST_DIR/victim/config.txt")" = "keep-me" ]
  [ ! -e "$TEST_DIR/repo/.lattice" ]
}


@test "check-only on a nonexistent root creates nothing and reports not ready" {
  MISSING="$TEST_DIR/never-made"
  run bash "$ENSURE" --check-only --root "$MISSING"
  [ "$status" -eq 1 ]
  [[ "$output" == *"not ready"* ]]
  [ ! -d "$MISSING" ]
}

@test "check-only --json on a nonexistent root emits ok:false JSON without creating it" {
  MISSING="$TEST_DIR/never-made-json"
  run bash "$ENSURE" --check-only --json --root "$MISSING"
  [ "$status" -eq 1 ]
  [[ "$output" == *'"ok": false'* ]]
  [ ! -d "$MISSING" ]
}
