#!/usr/bin/env bats
# bats tests for lattice-init.sh

setup_file() {
  REPO_ROOT="$(cd "$(dirname "$BATS_TEST_FILENAME")/../../../.." && pwd)"
  export INIT="$REPO_ROOT/skills/_lattice-lib/scripts/lattice-init.sh"
}

setup() {
  TEST_DIR="$(mktemp -d "${TMPDIR:-/tmp}/lattice-init.XXXXXX")"
  export TEST_DIR
  mkdir -p "$TEST_DIR/repo"
  # minimal git repo so --root works without requiring git inside
}

teardown() {
  rm -rf "$TEST_DIR"
}

@test "creates skeleton + config default strict" {
  run bash "$INIT" --root "$TEST_DIR/repo" --json
  [ "$status" -eq 0 ]
  [ -d "$TEST_DIR/repo/.lattice/specs" ]
  [ -d "$TEST_DIR/repo/.lattice/reviews" ]
  [ -d "$TEST_DIR/repo/.lattice/tickets" ]
  [ -d "$TEST_DIR/repo/.lattice/tickets" ]
  [ -f "$TEST_DIR/repo/.lattice/config.yaml" ]
  grep -q 'profile: strict' "$TEST_DIR/repo/.lattice/config.yaml"
  [ ! -e "$TEST_DIR/repo/.lattice/gitignore.snippet" ]
  [ -f "$TEST_DIR/repo/.lattice/README.md" ]
  printf '%s\n' "$output" | grep -qF '"ok": true' || printf '%s\n' "$output" | grep -qF '"ok": true'
}

@test "idempotent second run keeps existing config" {
  bash "$INIT" --root "$TEST_DIR/repo" --profile light >/dev/null
  grep -q 'profile: light' "$TEST_DIR/repo/.lattice/config.yaml"
  # second run with different profile must NOT overwrite
  run bash "$INIT" --root "$TEST_DIR/repo" --profile strict
  [ "$status" -eq 0 ]
  grep -q 'profile: light' "$TEST_DIR/repo/.lattice/config.yaml"
}

@test "write-gitignore appends once" {
  : >"$TEST_DIR/repo/.gitignore"
  bash "$INIT" --root "$TEST_DIR/repo" --write-gitignore >/dev/null
  grep -q 'Lattice (generated by lattice-init' "$TEST_DIR/repo/.gitignore"
  [ ! -e "$TEST_DIR/repo/.lattice/gitignore.snippet" ]
  lines1=$(wc -l <"$TEST_DIR/repo/.gitignore")
  bash "$INIT" --root "$TEST_DIR/repo" --write-gitignore >/dev/null
  lines2=$(wc -l <"$TEST_DIR/repo/.gitignore")
  [ "$lines1" -eq "$lines2" ]
}

@test "no --write-gitignore echoes block to stdout and creates no snippet file" {
  run bash "$INIT" --root "$TEST_DIR/repo"
  [ "$status" -eq 0 ]
  # block is echoed to stdout for manual merge
  printf '%s\n' "$output" | grep -qF '# --- Lattice (generated by lattice-init.sh'
  printf '%s\n' "$output" | grep -qF '.lattice/lineage/'
  # no persistent snippet file leaks into the consumer repo
  [ ! -e "$TEST_DIR/repo/.lattice/gitignore.snippet" ]
}

@test "--json never echoes the block (pure JSON on stdout)" {
  run bash "$INIT" --root "$TEST_DIR/repo" --json
  [ "$status" -eq 0 ]
  # stdout must be pure JSON: no inline ignore block. Use `if grep -q; then
  # false; fi` (not bare `! cmd`, banned by the bats-assertion-ergonomics
  # guard); avoid `run` here so $output is not clobbered for the next check.
  if printf '%s\n' "$output" | grep -qF '# --- Lattice (generated by lattice-init.sh'; then
    echo "Lattice ignore block leaked into --json stdout" >&3
    false
  fi
  printf '%s\n' "$output" | grep -qF '"gitignore_wrote": false'
  [ ! -e "$TEST_DIR/repo/.lattice/gitignore.snippet" ]
}

@test "migration removes a stray pre-existing .lattice/gitignore.snippet" {
  mkdir -p "$TEST_DIR/repo/.lattice"
  printf 'stale\n' >"$TEST_DIR/repo/.lattice/gitignore.snippet"
  run bash "$INIT" --root "$TEST_DIR/repo" --json
  [ "$status" -eq 0 ]
  [ ! -e "$TEST_DIR/repo/.lattice/gitignore.snippet" ]
}

@test "write-gitignore rejects a symlink without touching its external target" {
  mkdir -p "$TEST_DIR/victim"
  printf 'keep-me\n' >"$TEST_DIR/victim/config.txt"
  ln -s ../victim/config.txt "$TEST_DIR/repo/.gitignore"

  run bash "$INIT" --root "$TEST_DIR/repo" --write-gitignore --json

  [ "$status" -eq 1 ]
  printf '%s\n' "$output" | grep -qF "refusing symlinked managed path"
  [ "$(cat "$TEST_DIR/victim/config.txt")" = "keep-me" ]
  [ ! -e "$TEST_DIR/repo/.lattice" ]
}

@test "a gitignore symlink is untouched when gitignore merging is disabled" {
  mkdir -p "$TEST_DIR/victim"
  printf 'keep-me\n' >"$TEST_DIR/victim/config.txt"
  ln -s ../victim/config.txt "$TEST_DIR/repo/.gitignore"

  run bash "$INIT" --root "$TEST_DIR/repo" --json

  [ "$status" -eq 0 ]
  [ "$(cat "$TEST_DIR/victim/config.txt")" = "keep-me" ]
  [ -f "$TEST_DIR/repo/.lattice/config.yaml" ]
}

@test "initialization rejects a symlinked lattice root before external writes" {
  mkdir -p "$TEST_DIR/victim/lattice"
  ln -s ../victim/lattice "$TEST_DIR/repo/.lattice"

  run bash "$INIT" --root "$TEST_DIR/repo" --json

  [ "$status" -eq 1 ]
  printf '%s\n' "$output" | grep -qF "refusing symlinked managed path"
  [ -z "$(find "$TEST_DIR/victim/lattice" -mindepth 1 -print -quit)" ]
}

@test "initialization rejects symlinked managed children" {
  mkdir -p "$TEST_DIR/repo/.lattice" "$TEST_DIR/victim/specs"
  ln -s ../../victim/specs "$TEST_DIR/repo/.lattice/specs"

  run bash "$INIT" --root "$TEST_DIR/repo" --json

  [ "$status" -eq 1 ]
  printf '%s\n' "$output" | grep -qF "refusing symlinked managed path"
  [ -z "$(find "$TEST_DIR/victim/specs" -mindepth 1 -print -quit)" ]
}

@test "initialization rejects a symlinked preferences.md" {
  mkdir -p "$TEST_DIR/repo/.lattice" "$TEST_DIR/victim"
  printf 'keep-me\n' >"$TEST_DIR/victim/preferences.md"
  ln -s ../../victim/preferences.md "$TEST_DIR/repo/.lattice/preferences.md"

  run bash "$INIT" --root "$TEST_DIR/repo" --json

  [ "$status" -eq 1 ]
  printf '%s\n' "$output" | grep -qF "refusing symlinked managed path"
  [ "$(cat "$TEST_DIR/victim/preferences.md")" = "keep-me" ]
}

@test "sync-labels never executes a consumer-repository fallback" {
  PARTIAL_INSTALL="$TEST_DIR/partial/_lattice-lib/scripts"
  CONSUMER_SYNC="$TEST_DIR/repo/skills/create-tickets/scripts"
  mkdir -p "$PARTIAL_INSTALL" "$CONSUMER_SYNC"
  cp "$INIT" "$PARTIAL_INSTALL/lattice-init.sh"
  cat >"$CONSUMER_SYNC/sync-github-labels.sh" <<EOF
#!/usr/bin/env bash
printf 'executed\n' >"$TEST_DIR/consumer-sync-executed"
EOF

  run bash "$PARTIAL_INSTALL/lattice-init.sh" \
    --root "$TEST_DIR/repo" --sync-labels --json

  [ "$status" -eq 0 ]
  printf '%s\n' "$output" | grep -qF '"labels_ran": false'
  printf '%s\n' "$output" | grep -qF "sync script not found"
  [ ! -e "$TEST_DIR/consumer-sync-executed" ]
}

@test "sync-labels still executes the trusted sibling install helper" {
  PARTIAL_ROOT="$TEST_DIR/partial"
  PARTIAL_INSTALL="$PARTIAL_ROOT/_lattice-lib/scripts"
  TRUSTED_SYNC="$PARTIAL_ROOT/create-tickets/scripts"
  mkdir -p "$PARTIAL_INSTALL" "$TRUSTED_SYNC"
  cp "$INIT" "$PARTIAL_INSTALL/lattice-init.sh"
  cat >"$TRUSTED_SYNC/sync-github-labels.sh" <<EOF
#!/usr/bin/env bash
printf 'trusted\n' >"$TEST_DIR/trusted-sync-executed"
EOF

  run bash "$PARTIAL_INSTALL/lattice-init.sh" \
    --root "$TEST_DIR/repo" --sync-labels --json

  [ "$status" -eq 0 ]
  printf '%s\n' "$output" | grep -qF '"labels_ran": true'
  [ "$(cat "$TEST_DIR/trusted-sync-executed")" = "trusted" ]
}

@test "sync-labels resolves a symlinked entrypoint back to the trusted install" {
  INSTALL_ROOT="$TEST_DIR/install"
  INSTALL_SCRIPTS="$INSTALL_ROOT/_lattice-lib/scripts"
  TRUSTED_SYNC="$INSTALL_ROOT/create-tickets/scripts"
  CONSUMER_LIB="$TEST_DIR/repo/skills/_lattice-lib/scripts"
  CONSUMER_SYNC="$TEST_DIR/repo/skills/create-tickets/scripts"
  mkdir -p "$INSTALL_SCRIPTS" "$TRUSTED_SYNC" "$CONSUMER_LIB" "$CONSUMER_SYNC"
  cp "$INIT" "$INSTALL_SCRIPTS/lattice-init.sh"
  ln -s "$INSTALL_SCRIPTS/lattice-init.sh" "$CONSUMER_LIB/lattice-init.sh"
  cat >"$TRUSTED_SYNC/sync-github-labels.sh" <<EOF
#!/usr/bin/env bash
printf 'trusted\n' >"$TEST_DIR/trusted-sync-executed"
EOF
  cat >"$CONSUMER_SYNC/sync-github-labels.sh" <<EOF
#!/usr/bin/env bash
printf 'consumer\n' >"$TEST_DIR/consumer-sync-executed"
EOF

  run bash "$CONSUMER_LIB/lattice-init.sh" \
    --root "$TEST_DIR/repo" --sync-labels --json

  [ "$status" -eq 0 ]
  printf '%s\n' "$output" | grep -qF '"labels_ran": true'
  [ "$(cat "$TEST_DIR/trusted-sync-executed")" = "trusted" ]
  [ ! -e "$TEST_DIR/consumer-sync-executed" ]
}

@test "rejects bad profile" {
  run bash "$INIT" --root "$TEST_DIR/repo" --profile banana
  [ "$status" -eq 1 ]
}

@test "--json without python3 fails cleanly before any .lattice mutation" {
  FAKE_BIN="$TEST_DIR/nopython"
  mkdir -p "$FAKE_BIN"
  for tool in bash tr sed grep git cat cmp mkdir rm mv head dirname basename wc; do
    p=$(command -v "$tool" 2>/dev/null) || continue
    ln -s "$p" "$FAKE_BIN/$tool"
  done
  run env PATH="$FAKE_BIN" bash "$INIT" --root "$TEST_DIR/repo" --json
  [ "$status" -eq 1 ]
  printf '%s\n' "$output" | grep -qF "python3 is required"
  [ ! -d "$TEST_DIR/repo/.lattice" ]
}
